# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'newtimesheetapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON', '~> 4.0.0'
pod 'Toast-Swift', '~> 4.0.0'
pod 'FSCalendar'
  # Pods for newtimesheetapp

  target 'newtimesheetappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'newtimesheetappUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
